# Theming
font: MesloLGS NF 10
background: "#000000ff"
color: "#ffffff"
border: "#ffffff"
separator: " ➜ "
border_width: 1
corner_r: 5
padding: 10
rows_per_column: 5
column_padding: 25

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

# Try to guess the correct keyboard layout to use. Default is `false`.
auto_kbd_layout: true

menu:
#  - key: "w"
#    desc: WireGuard
#    cmd: bash -c "if ip link show desktop > /dev/null 2>&1; then sudo wg-quick down desktop; else sudo wg-quick up desktop; fi"

  - key: "w" 
    desc: WireGuard
    cmd: bash -c "if ip link show desktop > /dev/null 2>&1; then sudo wg-quick down desktop && notify-send 'WireGuard' 'Connection deactivated'; else sudo wg-quick up desktop && notify-send 'WireGuard' 'Connection activated'; fi"

  - key: "a"
    desc: audio output 
    submenu:
      - key: "1"
        desc: monitor-headphones
        cmd: pactl set-default-sink alsa_output.pci-0000_03_00.1.pro-output-3 

      - key: "2"
        desc: monitor
        cmd: pactl set-default-sink alsa_output.pci-0000_03_00.1.pro-output-7 

      - key: "3"
        desc: m-audio
        cmd: pactl set-default-sink alsa_output.usb-BurrBrown_from_Texas_Instruments_USB_AUDIO_CODEC-00.pro-output-0

  - key: "c"
    desc: Config
    submenu:
      - key: "c"
        desc: .config/
        cmd: foot -e sh -c "cd ~/.config && ls; exec \$SHELL"
      - key: "n"
        desc: niri.kdl
        cmd: foot -e nvim ~/.config/niri/config.kdl
      - key: "g"
        desc: GPU Frequency
        cmd: /usr/local/bin/set-gpu-freq.sh

  - key: "q"
    desc: kill niri 
    cmd:  killall niri

  - key: "p"
    desc: Power
    submenu:
      - key: "s"
        desc: Sleep
        cmd: systemctl suspend
      - key: "r"
        desc: Reboot
        cmd: reboot
      - key: "o"
        desc: Off
        cmd: poweroff
