# Theming
font: MesloLGS NF 12
background: "#282828d0"
color: "#fbf1c7"
border: "#8ec07c"
separator: " ➜ "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r
rows_per_column: 5 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

# Try to guess the correct keyboard layout to use. Default is `false`.
auto_kbd_layout: true

menu:

  - key: "i"
    desc: app id 
    cmd: niri msg focused-window

  - key: "q"
    desc: kill niri 
    cmd: killall niri

  - key: "p"
    desc: Power
    submenu:
      - key: "s"
        desc: Sleep
        cmd: systemctl suspend
      - key: "r"
        desc: Reboot
        cmd: reboot
      - key: "o"
        desc: Off
        cmd: poweroff
  - key: "c"
    desc: Config
    submenu:
      - key: "c"
        desc: .config/
        cmd: foot -e sh -c "cd ~/.config && ls; exec \$SHELL"
      - key: "n"
        desc: niri.kdl
        cmd: foot -e nvim ~/.config/niri/config.kdl
        #cmd: foot-client -e neovim ~/.config/niri/config.kdl
